### ISSUE TITLE
Healthy error after latest image update, no problems before.

### ISSUE THREAD

**Issue by Akruidenberg** [crazy-max/docker-firefox-syncserver#10]
#### Steps to reproduce this issue

1. start container
2.
3.

#### Expected behaviour

> starts without unhealthy error

#### Actual behaviour

> Get unhealthy error after latest docker image, before the update, no problems.

### Configuration

* Docker version 19.03.1 :
* Docker compose version if applicable 1.8.0 : 
* Platform Debian 9: 
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
> Output of command `docker info`
```

### Logs

```
Setting timezone to Europe/Amsterdam...,
  'x=%s' % value).load(False),
[2019-08-05 08:21:20 +0000] [12] [INFO] Booting worker with pid: 12,
/usr/local/lib/python2.7/site-packages/pyramid/path.py:341: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.,
[2019-08-05 08:21:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1),
[2019-08-05 08:21:20 +0000] [1] [INFO] Starting gunicorn 19.6.0,
Generating configuration...,
Checking prerequisites...,
[2019-08-05 08:21:20 +0000] [1] [INFO] Using worker: sync
```

Compose:

```yml
  firefoxsync:
    container_name: firefox
    restart: unless-stopped
    image: crazymax/firefox-syncserver
    volumes:
      - ${USERDIR}/firefoxsync:/data
    networks:
      - reverseproxy
    env_file:
      - "./firefoxsync.env"
    environment:
      - TZ=${TZ}
    labels:
    - "traefik.docker.network=reverseproxy"
    - "traefik.backend=firefox"
    - "traefik.enable=true"
    - "traefik.web.frontend.rule=Host:firefoxsync.******.com"
    - "traefik.web.port=5000"
    - "traefik.frontend.headers.SSLRedirect=true"
    - "traefik.frontend.headers.STSSeconds=315360000"
    - "traefik.frontend.headers.browserXSSFilter=true"
    - "traefik.frontend.headers.contentTypeNosniff=true"
    - "traefik.frontend.headers.forceSTSHeader=true"
    - "traefik.frontend.headers.SSLHost=***.com"
    - "traefik.frontend.headers.STSIncludeSubdomains=true"
    - "traefik.frontend.headers.STSPreload=true"
    - "traefik.frontend.headers.frameDeny=true"
```

.env file

```
FF_SYNCSERVER_PUBLIC_URL=https://firefoxsync.********.com
FF_SYNCSERVER_SECRET=***********
FF_SYNCSERVER_ALLOW_NEW_USERS=true
FF_SYNCSERVER_FORCE_WSGI_ENVIRON=true
FF_SYNCSERVER_FORCE_WSGI_ENVIRON=sqlite:///data/syncserver.db
```

**Comment by crazy-max** [comment]
Hi @Akruidenberg,

Can you give me the output of:

`docker inspect firefox | jq ".[]. State.Health"`

or

`docker inspect --format="{{json .State.Health}}" firefox`

**Comment by Akruidenberg** [comment]
This is my output:

{"Status":"unhealthy","FailingStreak":254,"Log":[{"Start":"2019-08-05T11:20:50.74008215+02:00","End":"2019-08-05T11:20:55.034317891+02:00","ExitCode":1,"Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\ncurl: (22) The requested URL returned error: 404 \n"},{"Start":"2019-08-05T11:21:05.04135562+02:00","End":"2019-08-05T11:21:09.34322146+02:00","ExitCode":1,"Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\ncurl: (22) The requested URL returned error: 404 \n"},{"Start":"2019-08-05T11:21:19.349510294+02:00","End":"2019-08-05T11:21:23.649836601+02:00","ExitCode":1,"Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\ncurl: (22) The requested URL returned error: 404 \n"},{"Start":"2019-08-05T11:21:33.657162742+02:00","End":"2019-08-05T11:21:37.946022519+02:00","ExitCode":1,"Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\ncurl: (22) The requested URL returned error: 404 \n"},{"Start":"2019-08-05T11:21:47.95309977+02:00","End":"2019-08-05T11:21:52.259942499+02:00","ExitCode":1,"Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\ncurl: (22) The requested URL returned error: 404 \n"}]}

**Comment by crazy-max** [comment]
Ok I think `FF_SYNCSERVER_PUBLIC_URL` env var is not taken into account by HEALTHCHECK with compose.
Can you rename `firefoxsync.env` to `.env` and change the value of `env_file` with `.env` in your compose and check if it's ok?

**Comment by Akruidenberg** [comment]
> 
> 
> Ok I think `FF_SYNCSERVER_PUBLIC_URL` env var is not taken into account by HEALTHCHECK with compose.
> Can you rename `firefoxsync.env` to `.env` and change the value of `env_file` with `.env` in your compose and check if it's ok?

Do you mean to ignore the env file and place the variables direcly into compose?

**Comment by Akruidenberg** [comment]
> Ok I think `FF_SYNCSERVER_PUBLIC_URL` env var is not taken into account by HEALTHCHECK with compose.
> Can you rename `firefoxsync.env` to `.env` and change the value of `env_file` with `.env` in your compose and check if it's ok?

no results. No changes are detected by compose

**Comment by crazy-max** [comment]
> Do you mean to ignore the env file and place the variables directly into compose?

Yep directly in your compose file, it seems to works for me (as a workaround for now) :

```yml
  firefoxsync:
    container_name: firefox
    restart: unless-stopped
    image: crazymax/firefox-syncserver
    volumes:
      - ${USERDIR}/firefoxsync:/data
    networks:
      - reverseproxy
    environment:
      - FF_SYNCSERVER_PUBLIC_URL=https://firefoxsync.********.com
      - FF_SYNCSERVER_SECRET=***********
      - FF_SYNCSERVER_ALLOW_NEW_USERS=true
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=sqlite:///data/syncserver.db
      - TZ=${TZ}
    labels:
    - "traefik.docker.network=reverseproxy"
    - "traefik.backend=firefox"
    - "traefik.enable=true"
    - "traefik.web.frontend.rule=Host:firefoxsync.******.com"
    - "traefik.web.port=5000"
    - "traefik.frontend.headers.SSLRedirect=true"
    - "traefik.frontend.headers.STSSeconds=315360000"
    - "traefik.frontend.headers.browserXSSFilter=true"
    - "traefik.frontend.headers.contentTypeNosniff=true"
    - "traefik.frontend.headers.forceSTSHeader=true"
    - "traefik.frontend.headers.SSLHost=***.com"
    - "traefik.frontend.headers.STSIncludeSubdomains=true"
    - "traefik.frontend.headers.STSPreload=true"
    - "traefik.frontend.headers.frameDeny=true"
```

You can also disable healthcheck if you want :

```yml
  firefoxsync:
    ...
    healthcheck:
      disable: true
```
