### ISSUE TITLE
Cannot start service traefik: driver failed programming external connectivity on endpoint

### ISSUE THREAD

**Issue by metal450** [crazy-max/docker-firefox-syncserver#2]
Upon running "docker-compose up," I seem to be getting the following errors:

```
Creating dockerfirefoxsyncserver_traefik_1            ... error
Creating firefox-syncserver ...

ERROR: for dockerfirefoxsyncserver_traefik_1  Cannot start service traefik: driver failed programming external connectivity on endpoint dockerfirefoxsyncserver_traefik_1 (372065602c403e7b6c05b6ae5864492940b12a3c13abcefcb99c1f42fcfec7fc): ErCreating firefox-syncserver ... done
use

ERROR: for traefik  Cannot start service traefik: driver failed programming external connectivity on endpoint dockerfirefoxsyncserver_traefik_1 (372065602c403e7b6c05b6ae5864492940b12a3c13abcefcb99c1f42fcfec7fc): Error starting userland proxy: listen tcp 0.0.0.0:443: listen: address already in use
ERROR: Encountered errors while bringing up the project.

```

I presume this is because port 443 is being used on the host (it's a QNap NAS), and the solution is that I just need to change one of the 443s to an available open port? For reference (since the setup seems to have changed a bit since the readme was written), the things I've currently changed in docker-compose.yml are:

```
traefik.port=5099
traefik.frontend.rule=Host:myexamplehost.com
FF_SYNCSERVER_PUBLIC_URL=https://myexamplehost.com:5099
FF_SYNCSERVER_SECRET=make a random i.e. 20-digit key
```

If my thinking is right, which of the 3x "443"s would need to be changed?
```
entryPoints=Name:https Address::443 TLS
target: 443
published: 443
```
?

**Comment by metal450** [comment]
...Tried it, now the error occurs with port 80 (understandably). However, I presume not all the port 80s need to be changed, because the syncserver itself will listen on 80, no? Or change all 3x of those to something random, too?

**Comment by crazy-max** [comment]
Can you post your docker-compose.yml please ?

**Comment by metal450** [comment]
Only mydomain.tld changed below:

```
version: '3.2'

services:
  traefik:
    image: traefik:1.6-alpine
    command:
      - --logLevel=INFO
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::5098 TLS
      - --docker
      - --docker.exposedbydefault=false
      - --docker.domain=example.com
      - --acme=true
      - --acme.acmelogging=true
      - --acme.email=webmaster@example.com
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onhostrule=true
      - --acme.httpchallenge=true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 5098
        published: 5098
        protocol: tcp
        mode: host
    volumes:
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox-syncserver
    volumes:
      - firefox-syncserver:/data
    labels:
      - traefik.enable=true
      - traefik.backend=firefox-syncserver
      - traefik.port=5099
      - traefik.frontend.rule=Host:mydomain.tld
    environment:
      - TZ=America/Los_Angeles
      - FF_SYNCSERVER_PUBLIC_URL=https://mydomain.tld:5099
      - FF_SYNCSERVER_SECRET=4280hf20ygf02rf
      - FF_SYNCSERVER_ALLOW_NEW_USERS=true
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=false
    restart: always

volumes:
  firefox-syncserver:

```
