### ISSUE TITLE
[Question] How to check if browser actually syncs with my server?

### ISSUE THREAD

**Issue by zilexa** [crazy-max/docker-firefox-syncserver#38]
I have successfully set up firefox-syncserver via docker compose and followed the info here to change the sync url on 1 of my devices: 
https://mozilla-services.readthedocs.io/en/latest/howtos/run-sync-1.5.html#howto-run-sync15

> 
> To configure desktop Firefox to talk to your new Sync server, go to “about:config”, search for “identity.sync.tokenserver.uri” and change its value to be the public URL of your server with a path of “token/1.0/sync/1.5”:
> 
>         identity.sync.tokenserver.uri: http://localhost:5000/token/1.0/sync/1.5
In my case the url is: https://firefox.mydomain.cloud:5000/token/1.0/sync/1.5
Snippet of my compose: 
```
##_____________________ Firefox Sync [CLOUD/Browser] 
# generate secret.txt first see docker-config.sh
  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox_syncserver
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FF_SYNCSERVER_PUBLIC_URL=https://firefox.$DOMAIN
      - FF_SYNCSERVER_SECRET=$FFSYNCSECRET
      - FF_SYNCSERVER_FORWARDED_ALLOW_IPS=*
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=true
    volumes:
      - "$USERDIR/docker/firefox-syncserver:/data"
    ports:
      - 5000:5000
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.firefox-redirect.redirectscheme.scheme=https
      - traefik.http.routers.firefox-redirect.entrypoints=web
      - traefik.http.routers.firefox-redirect.middlewares=firefox-redirect
      - traefik.http.routers.firefox-redirect.rule=Host(`firefox.$DOMAIN`)
      - traefik.http.routers.firefox.entrypoints=websecure
      - traefik.http.routers.firefox.rule=Host(`firefox.$DOMAIN`)
      - traefik.http.routers.firefox.tls.certresolver=letsencrypt
      - traefik.http.services.firefox.loadbalancer.server.port=5000
```

log file shows (notice the depricated environment warning, I did not state any depricated env vars in my Compose):
```
Setting timezone to Europe/Amsterdam...
Checking prerequisites...
Generating configuration...
Fixing perms...
[2020-10-21 15:54:39 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2020-10-21 15:54:39 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-10-21 15:54:39 +0000] [1] [INFO] Using worker: sync
[2020-10-21 15:54:39 +0000] [15] [INFO] Booting worker with pid: 15
/usr/local/lib/python2.7/site-packages/pyramid/path.py:341: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
'x=%s' % value).load(False)
```

But how can I verify if it is actually syncing everything to my server instead of a Mozilla server? I restarted my browser, manually initiated a sync via the menu. I can of course change the url on all my devices, but even if syncing still works.. is there a way to check within the Docker container whether things are happening or not?

**Comment by zilexa** [comment]
I was using Firefox Beta for Android. I installed Firefox for Android besides it and changed the url (after tapping the logo in About Firefox 5 times, this option becomes visible in Settings). 

Unfortunately, after authentication, "last sync" stays on Never (Firefox for Android). Even if I tap to sync. 

It seems now, both my desktop Firefox and my (new) Firefox for Android are not syncing. 
With my old Firefox Beta for Android, I logged out of Sync, changed the URL. Now after a login attempt (authentication), the Firefox Beta app itself is still not logged in. I am logged in and shown as Web Session when I go to my account page. 

What could have gone wrong here?

**Comment by doc75** [comment]
@zilexa , have you tried in your firefox to check the `about:sync-log` content ?
I have also a sync issue and can see error in the logs (but I do not know how to solve them :worried: )

**Comment by zilexa** [comment]
> @zilexa , have you tried in your firefox to check the `about:sync-log` content ?
> I have also a sync issue and can see error in the logs (but I do not know how to solve them 😟 )

Thanks I will try tomorrow. Had some other unrelated stuff to fix first.

**Comment by zilexa** [comment]
The issue remains with " application url is:    http://firefox.obelix.cloud" 
While it is https. How can I change the `application url` ?

**Comment by zilexa** [comment]
I have got it working. Not sure how or why. 

```
##_____________________ Firefox Sync [CLOUD/Browser] 
# generate secret.txt first see docker-config.sh
  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox_syncserver
    restart: always
    environment: 
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FF_SYNCSERVER_PUBLIC_URL=https://firefox.$DOMAIN
      - FF_SYNCSERVER_SECRET=$FFSYNCSECRET
#      - FF_SYNCSERVER_FORWARDED_ALLOW_IPS=*
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - FF_SYNCSERVER_ALLOW_NEW_USERS=true
      - FF_SYNCSERVER_LOGLEVEL=debug
    volumes:
      - "$USERDIR/docker/firefox-syncserver:/data"
    ports:
      - 5000:5000
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.firefox-redirect.redirectscheme.scheme=https
      - traefik.http.routers.firefox-redirect.entrypoints=web
      - traefik.http.routers.firefox-redirect.middlewares=firefox-redirect
      - traefik.http.routers.firefox-redirect.rule=Host(`firefox.$DOMAIN`)
      - traefik.http.routers.firefox.entrypoints=websecure
      - traefik.http.routers.firefox.rule=Host(`firefox.$DOMAIN`)
      - traefik.http.routers.firefox.tls.certresolver=letsencrypt
      - traefik.http.services.firefox.loadbalancer.server.port=5000
```

Did not chang any Traefik label. 
Note on Android I accidentally changed the Auth server. Be careful to select sync server. 
You will get both options via Firefox > Settings > About > tap the logo 5 times > go back to Settings > see the extra options under Sync > Only change the sync server to https://firefox.yourdomain.com/token/token/1.0/sync/1.5

You can also test in a browser: 
https://firefox.yourdomain.com/token/ 
should not show any errors.
