### ISSUE TITLE
Installation success, but Firefox Android 82.1.3 not syncing

### ISSUE THREAD

**Issue by zilexa** [crazy-max/docker-firefox-syncserver#41]
#### Steps to reproduce this issue

1. Install this docker image
2. On your devices (1 pc, 1 laptop, 1 Android 10 (Pixel 1))  log out of your Firefox account. 
3. Change the sync url of your devices (on Android, tap the About Firefox logo in Settings 5x first). 
4. Restart Firefox.
5. Login to your account. 

#### Expected behaviour
Syncing should work between all three devices.

#### Actual behaviour
Syncing works between the desktop devices (I add a bookmark on one, inititate sync manually, then inititiate sync manually on the other desktop and the bookmark appears). 
Problem:
On Android, "last time sync" shows 1 jan 1970 and syncing stops immediately when you hit the Sync Now button and it then says "last time sync: Never."
It seems it does not connect to my server at all.

### Configuration
I can access `https://firefox.obelix.cloud/token/`
There are no errors.
I am on Ubuntu 20.04.1
```
  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox_syncserver
    restart: always
    environment: 
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FF_SYNCSERVER_PUBLIC_URL=https://firefox.$DOMAIN
      - FF_SYNCSERVER_SECRET=$FFSYNCSECRET
#      - FF_SYNCSERVER_FORWARDED_ALLOW_IPS=*
      - FF_SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - FF_SYNCSERVER_ALLOW_NEW_USERS=true
      - FF_SYNCSERVER_LOGLEVEL=debug
    volumes:
      - "$USERDIR/docker/firefox-syncserver:/data"
    ports:
      - 5000:5000
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.firefox-redirect.redirectscheme.scheme=https
      - traefik.http.routers.firefox-redirect.entrypoints=web
      - traefik.http.routers.firefox-redirect.middlewares=firefox-redirect
      - traefik.http.routers.firefox-redirect.rule=Host(`firefox.$DOMAIN`)
      - traefik.http.routers.firefox.entrypoints=websecure
      - traefik.http.routers.firefox.rule=Host(`firefox.$DOMAIN`)
      - traefik.http.routers.firefox.tls.certresolver=letsencrypt
      - traefik.http.services.firefox.loadbalancer.server.port=5000
```

### Logs
about:sync-log does not work on Firefox for Android.
