### ISSUE TITLE
[idea] add Caddy to examples 

### ISSUE THREAD

**Issue by zilexa** [crazy-max/docker-firefox-syncserver#44]
I recently switched from Traefik to Caddy as it is unbelievably simple to set up. I think others would benefit from an extra example in your documentation, next to Traefik. This is really all you need, no need to install Caddy on the host, no need to create a Caddy config file:

```
##_____________________ Caddy [CLOUD/web-proxy]
  caddy:
    container_name: caddy-proxy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    networks: 
      - web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/caddy/caddy_data:/data
      - $DOCKERDIR/caddy/config:/config
    labels:
      caddy.email: $EMAIL
    ports:
      - 80:80
      - 443:443
##_____________________ Firefox Sync [CLOUD/Browser] 
# generate secret.txt first see docker-config.sh
  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox_syncserver
    restart: always
    networks: 
      - web-proxy
    environment: 
      FF_SYNCSERVER_PUBLIC_URL: firefox.$DOMAIN
      FF_SYNCSERVER_SECRET: $FFSYNCSECRET
      FF_SYNCSERVER_FORWARDED_ALLOW_IPS: '*'
      FF_SYNCSERVER_FORCE_WSGI_ENVIRON: 'true'
      FF_SYNCSERVER_ALLOW_NEW_USERS: 'true'
      FF_SYNCSERVER_LOGLEVEL: debug
      FF_SYNCSERVER_ACCESSLOG: 'true'
    volumes:
      - $DOCKERDIR/firefox-syncserver:/data
    labels:
      caddy: firefox.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 5000}}"
```
