### ISSUE TITLE
The public_url setting doesn't match the application url

### ISSUE THREAD

**Issue by truthsword** [crazy-max/docker-firefox-syncserver#60]
Running Docker on an RPi.

No apparent sync. The DB file size is unchanged (61440) from fresh start. 

Docker compose...
```
version: "3.2"
services:
  firefox-syncserver:
    image: crazymax/firefox-syncserver:latest
    container_name: firefox_syncserver
    ports:
      - 5000:5000
    environment:
      - PUID=1000
      - PGID=1000
      - FF_SYNCSERVER_PUBLIC_URL='http://192.168.1.10:5000'
      - FF_SYNCSERVER_SECRET='somerandomstufftypedhere'
      - TZ=America/Chicago
    volumes:
      - /home/david/docker/ffsync/data:/data
    restart: always
```
I'm using `http://192.168.1.10:5000/token/1.0/sync/1.5/` in the `identity.sync.tokenserver.uri` section of `about:config`. I tried this with and without the trailing slash after `1.5`.

I must be missing something obvious. It can't be this hard... can it? Thanks!
